// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PbPlayerEntity.proto

package com.xmbl.ops.proto;

public final class PbPlayerEntity {
  private PbPlayerEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PbPlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PbPlayer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *角色唯一id
     * </pre>
     *
     * <code>required int64 Id = 1;</code>
     */
    boolean hasId();
    /**
     * <pre>
     *角色唯一id
     * </pre>
     *
     * <code>required int64 Id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     *角色名称
     * </pre>
     *
     * <code>optional string Name = 2;</code>
     */
    boolean hasName();
    /**
     * <pre>
     *角色名称
     * </pre>
     *
     * <code>optional string Name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     *角色名称
     * </pre>
     *
     * <code>optional string Name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *角色等级
     * </pre>
     *
     * <code>optional int32 Level = 3;</code>
     */
    boolean hasLevel();
    /**
     * <pre>
     *角色等级
     * </pre>
     *
     * <code>optional int32 Level = 3;</code>
     */
    int getLevel();

    /**
     * <pre>
     *服务器ID
     * </pre>
     *
     * <code>optional int32 ServerId = 4;</code>
     */
    boolean hasServerId();
    /**
     * <pre>
     *服务器ID
     * </pre>
     *
     * <code>optional int32 ServerId = 4;</code>
     */
    int getServerId();

    /**
     * <pre>
     *当前所在服ID   有可能处于战斗服
     * </pre>
     *
     * <code>optional int32 CurServerId = 5;</code>
     */
    boolean hasCurServerId();
    /**
     * <pre>
     *当前所在服ID   有可能处于战斗服
     * </pre>
     *
     * <code>optional int32 CurServerId = 5;</code>
     */
    int getCurServerId();

    /**
     * <pre>
     *天梯等级
     * </pre>
     *
     * <code>optional int32 LadderLv = 6;</code>
     */
    boolean hasLadderLv();
    /**
     * <pre>
     *天梯等级
     * </pre>
     *
     * <code>optional int32 LadderLv = 6;</code>
     */
    int getLadderLv();

    /**
     * <pre>
     *天梯星数
     * </pre>
     *
     * <code>optional int32 LadderStar = 7;</code>
     */
    boolean hasLadderStar();
    /**
     * <pre>
     *天梯星数
     * </pre>
     *
     * <code>optional int32 LadderStar = 7;</code>
     */
    int getLadderStar();

    /**
     * <pre>
     *头像图片
     * </pre>
     *
     * <code>optional string Avatar = 8;</code>
     */
    boolean hasAvatar();
    /**
     * <pre>
     *头像图片
     * </pre>
     *
     * <code>optional string Avatar = 8;</code>
     */
    java.lang.String getAvatar();
    /**
     * <pre>
     *头像图片
     * </pre>
     *
     * <code>optional string Avatar = 8;</code>
     */
    com.google.protobuf.ByteString
        getAvatarBytes();

    /**
     * <pre>
     *状态
     * </pre>
     *
     * <code>optional int32 State = 9;</code>
     */
    boolean hasState();
    /**
     * <pre>
     *状态
     * </pre>
     *
     * <code>optional int32 State = 9;</code>
     */
    int getState();

    /**
     * <pre>
     *是否需要新手引导
     * </pre>
     *
     * <code>optional bool NeedGuild = 10;</code>
     */
    boolean hasNeedGuild();
    /**
     * <pre>
     *是否需要新手引导
     * </pre>
     *
     * <code>optional bool NeedGuild = 10;</code>
     */
    boolean getNeedGuild();

    /**
     * <pre>
     *排行信息
     * </pre>
     *
     * <code>optional int32 Rank = 11;</code>
     */
    boolean hasRank();
    /**
     * <pre>
     *排行信息
     * </pre>
     *
     * <code>optional int32 Rank = 11;</code>
     */
    int getRank();

    /**
     * <pre>
     *角色人物模型
     * </pre>
     *
     * <code>optional int32 Model = 12;</code>
     */
    boolean hasModel();
    /**
     * <pre>
     *角色人物模型
     * </pre>
     *
     * <code>optional int32 Model = 12;</code>
     */
    int getModel();

    /**
     * <pre>
     *星座
     * </pre>
     *
     * <code>optional int32 Nationality = 13;</code>
     */
    boolean hasNationality();
    /**
     * <pre>
     *星座
     * </pre>
     *
     * <code>optional int32 Nationality = 13;</code>
     */
    int getNationality();

    /**
     * <pre>
     *装扮
     * </pre>
     *
     * <code>repeated int32 Avaters = 14;</code>
     */
    java.util.List<java.lang.Integer> getAvatersList();
    /**
     * <pre>
     *装扮
     * </pre>
     *
     * <code>repeated int32 Avaters = 14;</code>
     */
    int getAvatersCount();
    /**
     * <pre>
     *装扮
     * </pre>
     *
     * <code>repeated int32 Avaters = 14;</code>
     */
    int getAvaters(int index);

    /**
     * <pre>
     *签名
     * </pre>
     *
     * <code>optional string Signature = 15;</code>
     */
    boolean hasSignature();
    /**
     * <pre>
     *签名
     * </pre>
     *
     * <code>optional string Signature = 15;</code>
     */
    java.lang.String getSignature();
    /**
     * <pre>
     *签名
     * </pre>
     *
     * <code>optional string Signature = 15;</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();

    /**
     * <pre>
     *国家
     * </pre>
     *
     * <code>optional int32 Constellation = 16;</code>
     */
    boolean hasConstellation();
    /**
     * <pre>
     *国家
     * </pre>
     *
     * <code>optional int32 Constellation = 16;</code>
     */
    int getConstellation();

    /**
     * <pre>
     *年龄
     * </pre>
     *
     * <code>optional int32 Age = 17;</code>
     */
    boolean hasAge();
    /**
     * <pre>
     *年龄
     * </pre>
     *
     * <code>optional int32 Age = 17;</code>
     */
    int getAge();

    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>optional int32 Sex = 18;</code>
     */
    boolean hasSex();
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>optional int32 Sex = 18;</code>
     */
    int getSex();

    /**
     * <pre>
     *城市
     * </pre>
     *
     * <code>optional string City = 19;</code>
     */
    boolean hasCity();
    /**
     * <pre>
     *城市
     * </pre>
     *
     * <code>optional string City = 19;</code>
     */
    java.lang.String getCity();
    /**
     * <pre>
     *城市
     * </pre>
     *
     * <code>optional string City = 19;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <pre>
     *坐标经度
     * </pre>
     *
     * <code>optional float GenLon = 20;</code>
     */
    boolean hasGenLon();
    /**
     * <pre>
     *坐标经度
     * </pre>
     *
     * <code>optional float GenLon = 20;</code>
     */
    float getGenLon();

    /**
     * <pre>
     *坐标纬度
     * </pre>
     *
     * <code>optional float GenLat = 21;</code>
     */
    boolean hasGenLat();
    /**
     * <pre>
     *坐标纬度
     * </pre>
     *
     * <code>optional float GenLat = 21;</code>
     */
    float getGenLat();

    /**
     * <pre>
     *天梯分数
     * </pre>
     *
     * <code>optional int32 LadderAddStarScore = 22;</code>
     */
    boolean hasLadderAddStarScore();
    /**
     * <pre>
     *天梯分数
     * </pre>
     *
     * <code>optional int32 LadderAddStarScore = 22;</code>
     */
    int getLadderAddStarScore();
  }
  /**
   * <pre>
   *角色
   * </pre>
   *
   * Protobuf type {@code PbPlayer}
   */
  public  static final class PbPlayer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PbPlayer)
      PbPlayerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PbPlayer.newBuilder() to construct.
    private PbPlayer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PbPlayer() {
      id_ = 0L;
      name_ = "";
      level_ = 0;
      serverId_ = 0;
      curServerId_ = 0;
      ladderLv_ = 0;
      ladderStar_ = 0;
      avatar_ = "";
      state_ = 0;
      needGuild_ = false;
      rank_ = 0;
      model_ = 0;
      nationality_ = 0;
      avaters_ = java.util.Collections.emptyList();
      signature_ = "";
      constellation_ = 0;
      age_ = 0;
      sex_ = 0;
      city_ = "";
      genLon_ = 0F;
      genLat_ = 0F;
      ladderAddStarScore_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PbPlayer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              level_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              serverId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              curServerId_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              ladderLv_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              ladderStar_ = input.readInt32();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              avatar_ = bs;
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              state_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              needGuild_ = input.readBool();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              rank_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              model_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              nationality_ = input.readInt32();
              break;
            }
            case 112: {
              if (!((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
                avaters_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00002000;
              }
              avaters_.add(input.readInt32());
              break;
            }
            case 114: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00002000) == 0x00002000) && input.getBytesUntilLimit() > 0) {
                avaters_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00002000;
              }
              while (input.getBytesUntilLimit() > 0) {
                avaters_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 122: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00002000;
              signature_ = bs;
              break;
            }
            case 128: {
              bitField0_ |= 0x00004000;
              constellation_ = input.readInt32();
              break;
            }
            case 136: {
              bitField0_ |= 0x00008000;
              age_ = input.readInt32();
              break;
            }
            case 144: {
              bitField0_ |= 0x00010000;
              sex_ = input.readInt32();
              break;
            }
            case 154: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00020000;
              city_ = bs;
              break;
            }
            case 165: {
              bitField0_ |= 0x00040000;
              genLon_ = input.readFloat();
              break;
            }
            case 173: {
              bitField0_ |= 0x00080000;
              genLat_ = input.readFloat();
              break;
            }
            case 176: {
              bitField0_ |= 0x00100000;
              ladderAddStarScore_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
          avaters_ = java.util.Collections.unmodifiableList(avaters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xmbl.ops.proto.PbPlayerEntity.internal_static_PbPlayer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xmbl.ops.proto.PbPlayerEntity.internal_static_PbPlayer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xmbl.ops.proto.PbPlayerEntity.PbPlayer.class, com.xmbl.ops.proto.PbPlayerEntity.PbPlayer.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     *角色唯一id
     * </pre>
     *
     * <code>required int64 Id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *角色唯一id
     * </pre>
     *
     * <code>required int64 Id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *角色名称
     * </pre>
     *
     * <code>optional string Name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *角色名称
     * </pre>
     *
     * <code>optional string Name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *角色名称
     * </pre>
     *
     * <code>optional string Name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 3;
    private int level_;
    /**
     * <pre>
     *角色等级
     * </pre>
     *
     * <code>optional int32 Level = 3;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *角色等级
     * </pre>
     *
     * <code>optional int32 Level = 3;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int SERVERID_FIELD_NUMBER = 4;
    private int serverId_;
    /**
     * <pre>
     *服务器ID
     * </pre>
     *
     * <code>optional int32 ServerId = 4;</code>
     */
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *服务器ID
     * </pre>
     *
     * <code>optional int32 ServerId = 4;</code>
     */
    public int getServerId() {
      return serverId_;
    }

    public static final int CURSERVERID_FIELD_NUMBER = 5;
    private int curServerId_;
    /**
     * <pre>
     *当前所在服ID   有可能处于战斗服
     * </pre>
     *
     * <code>optional int32 CurServerId = 5;</code>
     */
    public boolean hasCurServerId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *当前所在服ID   有可能处于战斗服
     * </pre>
     *
     * <code>optional int32 CurServerId = 5;</code>
     */
    public int getCurServerId() {
      return curServerId_;
    }

    public static final int LADDERLV_FIELD_NUMBER = 6;
    private int ladderLv_;
    /**
     * <pre>
     *天梯等级
     * </pre>
     *
     * <code>optional int32 LadderLv = 6;</code>
     */
    public boolean hasLadderLv() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     *天梯等级
     * </pre>
     *
     * <code>optional int32 LadderLv = 6;</code>
     */
    public int getLadderLv() {
      return ladderLv_;
    }

    public static final int LADDERSTAR_FIELD_NUMBER = 7;
    private int ladderStar_;
    /**
     * <pre>
     *天梯星数
     * </pre>
     *
     * <code>optional int32 LadderStar = 7;</code>
     */
    public boolean hasLadderStar() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     *天梯星数
     * </pre>
     *
     * <code>optional int32 LadderStar = 7;</code>
     */
    public int getLadderStar() {
      return ladderStar_;
    }

    public static final int AVATAR_FIELD_NUMBER = 8;
    private volatile java.lang.Object avatar_;
    /**
     * <pre>
     *头像图片
     * </pre>
     *
     * <code>optional string Avatar = 8;</code>
     */
    public boolean hasAvatar() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     *头像图片
     * </pre>
     *
     * <code>optional string Avatar = 8;</code>
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          avatar_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *头像图片
     * </pre>
     *
     * <code>optional string Avatar = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 9;
    private int state_;
    /**
     * <pre>
     *状态
     * </pre>
     *
     * <code>optional int32 State = 9;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <pre>
     *状态
     * </pre>
     *
     * <code>optional int32 State = 9;</code>
     */
    public int getState() {
      return state_;
    }

    public static final int NEEDGUILD_FIELD_NUMBER = 10;
    private boolean needGuild_;
    /**
     * <pre>
     *是否需要新手引导
     * </pre>
     *
     * <code>optional bool NeedGuild = 10;</code>
     */
    public boolean hasNeedGuild() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <pre>
     *是否需要新手引导
     * </pre>
     *
     * <code>optional bool NeedGuild = 10;</code>
     */
    public boolean getNeedGuild() {
      return needGuild_;
    }

    public static final int RANK_FIELD_NUMBER = 11;
    private int rank_;
    /**
     * <pre>
     *排行信息
     * </pre>
     *
     * <code>optional int32 Rank = 11;</code>
     */
    public boolean hasRank() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <pre>
     *排行信息
     * </pre>
     *
     * <code>optional int32 Rank = 11;</code>
     */
    public int getRank() {
      return rank_;
    }

    public static final int MODEL_FIELD_NUMBER = 12;
    private int model_;
    /**
     * <pre>
     *角色人物模型
     * </pre>
     *
     * <code>optional int32 Model = 12;</code>
     */
    public boolean hasModel() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <pre>
     *角色人物模型
     * </pre>
     *
     * <code>optional int32 Model = 12;</code>
     */
    public int getModel() {
      return model_;
    }

    public static final int NATIONALITY_FIELD_NUMBER = 13;
    private int nationality_;
    /**
     * <pre>
     *星座
     * </pre>
     *
     * <code>optional int32 Nationality = 13;</code>
     */
    public boolean hasNationality() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <pre>
     *星座
     * </pre>
     *
     * <code>optional int32 Nationality = 13;</code>
     */
    public int getNationality() {
      return nationality_;
    }

    public static final int AVATERS_FIELD_NUMBER = 14;
    private java.util.List<java.lang.Integer> avaters_;
    /**
     * <pre>
     *装扮
     * </pre>
     *
     * <code>repeated int32 Avaters = 14;</code>
     */
    public java.util.List<java.lang.Integer>
        getAvatersList() {
      return avaters_;
    }
    /**
     * <pre>
     *装扮
     * </pre>
     *
     * <code>repeated int32 Avaters = 14;</code>
     */
    public int getAvatersCount() {
      return avaters_.size();
    }
    /**
     * <pre>
     *装扮
     * </pre>
     *
     * <code>repeated int32 Avaters = 14;</code>
     */
    public int getAvaters(int index) {
      return avaters_.get(index);
    }

    public static final int SIGNATURE_FIELD_NUMBER = 15;
    private volatile java.lang.Object signature_;
    /**
     * <pre>
     *签名
     * </pre>
     *
     * <code>optional string Signature = 15;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <pre>
     *签名
     * </pre>
     *
     * <code>optional string Signature = 15;</code>
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signature_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *签名
     * </pre>
     *
     * <code>optional string Signature = 15;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONSTELLATION_FIELD_NUMBER = 16;
    private int constellation_;
    /**
     * <pre>
     *国家
     * </pre>
     *
     * <code>optional int32 Constellation = 16;</code>
     */
    public boolean hasConstellation() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <pre>
     *国家
     * </pre>
     *
     * <code>optional int32 Constellation = 16;</code>
     */
    public int getConstellation() {
      return constellation_;
    }

    public static final int AGE_FIELD_NUMBER = 17;
    private int age_;
    /**
     * <pre>
     *年龄
     * </pre>
     *
     * <code>optional int32 Age = 17;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <pre>
     *年龄
     * </pre>
     *
     * <code>optional int32 Age = 17;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int SEX_FIELD_NUMBER = 18;
    private int sex_;
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>optional int32 Sex = 18;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>optional int32 Sex = 18;</code>
     */
    public int getSex() {
      return sex_;
    }

    public static final int CITY_FIELD_NUMBER = 19;
    private volatile java.lang.Object city_;
    /**
     * <pre>
     *城市
     * </pre>
     *
     * <code>optional string City = 19;</code>
     */
    public boolean hasCity() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <pre>
     *城市
     * </pre>
     *
     * <code>optional string City = 19;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          city_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *城市
     * </pre>
     *
     * <code>optional string City = 19;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENLON_FIELD_NUMBER = 20;
    private float genLon_;
    /**
     * <pre>
     *坐标经度
     * </pre>
     *
     * <code>optional float GenLon = 20;</code>
     */
    public boolean hasGenLon() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    /**
     * <pre>
     *坐标经度
     * </pre>
     *
     * <code>optional float GenLon = 20;</code>
     */
    public float getGenLon() {
      return genLon_;
    }

    public static final int GENLAT_FIELD_NUMBER = 21;
    private float genLat_;
    /**
     * <pre>
     *坐标纬度
     * </pre>
     *
     * <code>optional float GenLat = 21;</code>
     */
    public boolean hasGenLat() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    /**
     * <pre>
     *坐标纬度
     * </pre>
     *
     * <code>optional float GenLat = 21;</code>
     */
    public float getGenLat() {
      return genLat_;
    }

    public static final int LADDERADDSTARSCORE_FIELD_NUMBER = 22;
    private int ladderAddStarScore_;
    /**
     * <pre>
     *天梯分数
     * </pre>
     *
     * <code>optional int32 LadderAddStarScore = 22;</code>
     */
    public boolean hasLadderAddStarScore() {
      return ((bitField0_ & 0x00100000) == 0x00100000);
    }
    /**
     * <pre>
     *天梯分数
     * </pre>
     *
     * <code>optional int32 LadderAddStarScore = 22;</code>
     */
    public int getLadderAddStarScore() {
      return ladderAddStarScore_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, serverId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, curServerId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, ladderLv_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, ladderStar_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, avatar_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, state_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBool(10, needGuild_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, rank_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, model_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, nationality_);
      }
      for (int i = 0; i < avaters_.size(); i++) {
        output.writeInt32(14, avaters_.get(i));
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, signature_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(16, constellation_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt32(17, age_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeInt32(18, sex_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 19, city_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeFloat(20, genLon_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        output.writeFloat(21, genLat_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        output.writeInt32(22, ladderAddStarScore_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, serverId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, curServerId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, ladderLv_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, ladderStar_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, avatar_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, state_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, needGuild_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, rank_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, model_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, nationality_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < avaters_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(avaters_.get(i));
        }
        size += dataSize;
        size += 1 * getAvatersList().size();
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, signature_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, constellation_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, age_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, sex_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, city_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(20, genLon_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(21, genLat_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(22, ladderAddStarScore_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xmbl.ops.proto.PbPlayerEntity.PbPlayer)) {
        return super.equals(obj);
      }
      com.xmbl.ops.proto.PbPlayerEntity.PbPlayer other = (com.xmbl.ops.proto.PbPlayerEntity.PbPlayer) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasLevel() == other.hasLevel());
      if (hasLevel()) {
        result = result && (getLevel()
            == other.getLevel());
      }
      result = result && (hasServerId() == other.hasServerId());
      if (hasServerId()) {
        result = result && (getServerId()
            == other.getServerId());
      }
      result = result && (hasCurServerId() == other.hasCurServerId());
      if (hasCurServerId()) {
        result = result && (getCurServerId()
            == other.getCurServerId());
      }
      result = result && (hasLadderLv() == other.hasLadderLv());
      if (hasLadderLv()) {
        result = result && (getLadderLv()
            == other.getLadderLv());
      }
      result = result && (hasLadderStar() == other.hasLadderStar());
      if (hasLadderStar()) {
        result = result && (getLadderStar()
            == other.getLadderStar());
      }
      result = result && (hasAvatar() == other.hasAvatar());
      if (hasAvatar()) {
        result = result && getAvatar()
            .equals(other.getAvatar());
      }
      result = result && (hasState() == other.hasState());
      if (hasState()) {
        result = result && (getState()
            == other.getState());
      }
      result = result && (hasNeedGuild() == other.hasNeedGuild());
      if (hasNeedGuild()) {
        result = result && (getNeedGuild()
            == other.getNeedGuild());
      }
      result = result && (hasRank() == other.hasRank());
      if (hasRank()) {
        result = result && (getRank()
            == other.getRank());
      }
      result = result && (hasModel() == other.hasModel());
      if (hasModel()) {
        result = result && (getModel()
            == other.getModel());
      }
      result = result && (hasNationality() == other.hasNationality());
      if (hasNationality()) {
        result = result && (getNationality()
            == other.getNationality());
      }
      result = result && getAvatersList()
          .equals(other.getAvatersList());
      result = result && (hasSignature() == other.hasSignature());
      if (hasSignature()) {
        result = result && getSignature()
            .equals(other.getSignature());
      }
      result = result && (hasConstellation() == other.hasConstellation());
      if (hasConstellation()) {
        result = result && (getConstellation()
            == other.getConstellation());
      }
      result = result && (hasAge() == other.hasAge());
      if (hasAge()) {
        result = result && (getAge()
            == other.getAge());
      }
      result = result && (hasSex() == other.hasSex());
      if (hasSex()) {
        result = result && (getSex()
            == other.getSex());
      }
      result = result && (hasCity() == other.hasCity());
      if (hasCity()) {
        result = result && getCity()
            .equals(other.getCity());
      }
      result = result && (hasGenLon() == other.hasGenLon());
      if (hasGenLon()) {
        result = result && (
            java.lang.Float.floatToIntBits(getGenLon())
            == java.lang.Float.floatToIntBits(
                other.getGenLon()));
      }
      result = result && (hasGenLat() == other.hasGenLat());
      if (hasGenLat()) {
        result = result && (
            java.lang.Float.floatToIntBits(getGenLat())
            == java.lang.Float.floatToIntBits(
                other.getGenLat()));
      }
      result = result && (hasLadderAddStarScore() == other.hasLadderAddStarScore());
      if (hasLadderAddStarScore()) {
        result = result && (getLadderAddStarScore()
            == other.getLadderAddStarScore());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasLevel()) {
        hash = (37 * hash) + LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getLevel();
      }
      if (hasServerId()) {
        hash = (37 * hash) + SERVERID_FIELD_NUMBER;
        hash = (53 * hash) + getServerId();
      }
      if (hasCurServerId()) {
        hash = (37 * hash) + CURSERVERID_FIELD_NUMBER;
        hash = (53 * hash) + getCurServerId();
      }
      if (hasLadderLv()) {
        hash = (37 * hash) + LADDERLV_FIELD_NUMBER;
        hash = (53 * hash) + getLadderLv();
      }
      if (hasLadderStar()) {
        hash = (37 * hash) + LADDERSTAR_FIELD_NUMBER;
        hash = (53 * hash) + getLadderStar();
      }
      if (hasAvatar()) {
        hash = (37 * hash) + AVATAR_FIELD_NUMBER;
        hash = (53 * hash) + getAvatar().hashCode();
      }
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState();
      }
      if (hasNeedGuild()) {
        hash = (37 * hash) + NEEDGUILD_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getNeedGuild());
      }
      if (hasRank()) {
        hash = (37 * hash) + RANK_FIELD_NUMBER;
        hash = (53 * hash) + getRank();
      }
      if (hasModel()) {
        hash = (37 * hash) + MODEL_FIELD_NUMBER;
        hash = (53 * hash) + getModel();
      }
      if (hasNationality()) {
        hash = (37 * hash) + NATIONALITY_FIELD_NUMBER;
        hash = (53 * hash) + getNationality();
      }
      if (getAvatersCount() > 0) {
        hash = (37 * hash) + AVATERS_FIELD_NUMBER;
        hash = (53 * hash) + getAvatersList().hashCode();
      }
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      if (hasConstellation()) {
        hash = (37 * hash) + CONSTELLATION_FIELD_NUMBER;
        hash = (53 * hash) + getConstellation();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (hasSex()) {
        hash = (37 * hash) + SEX_FIELD_NUMBER;
        hash = (53 * hash) + getSex();
      }
      if (hasCity()) {
        hash = (37 * hash) + CITY_FIELD_NUMBER;
        hash = (53 * hash) + getCity().hashCode();
      }
      if (hasGenLon()) {
        hash = (37 * hash) + GENLON_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getGenLon());
      }
      if (hasGenLat()) {
        hash = (37 * hash) + GENLAT_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getGenLat());
      }
      if (hasLadderAddStarScore()) {
        hash = (37 * hash) + LADDERADDSTARSCORE_FIELD_NUMBER;
        hash = (53 * hash) + getLadderAddStarScore();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xmbl.ops.proto.PbPlayerEntity.PbPlayer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xmbl.ops.proto.PbPlayerEntity.PbPlayer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xmbl.ops.proto.PbPlayerEntity.PbPlayer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xmbl.ops.proto.PbPlayerEntity.PbPlayer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xmbl.ops.proto.PbPlayerEntity.PbPlayer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xmbl.ops.proto.PbPlayerEntity.PbPlayer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xmbl.ops.proto.PbPlayerEntity.PbPlayer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xmbl.ops.proto.PbPlayerEntity.PbPlayer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xmbl.ops.proto.PbPlayerEntity.PbPlayer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xmbl.ops.proto.PbPlayerEntity.PbPlayer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xmbl.ops.proto.PbPlayerEntity.PbPlayer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xmbl.ops.proto.PbPlayerEntity.PbPlayer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xmbl.ops.proto.PbPlayerEntity.PbPlayer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *角色
     * </pre>
     *
     * Protobuf type {@code PbPlayer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PbPlayer)
        com.xmbl.ops.proto.PbPlayerEntity.PbPlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xmbl.ops.proto.PbPlayerEntity.internal_static_PbPlayer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xmbl.ops.proto.PbPlayerEntity.internal_static_PbPlayer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xmbl.ops.proto.PbPlayerEntity.PbPlayer.class, com.xmbl.ops.proto.PbPlayerEntity.PbPlayer.Builder.class);
      }

      // Construct using com.xmbl.ops.proto.PbPlayerEntity.PbPlayer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        curServerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        ladderLv_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        ladderStar_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        avatar_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        needGuild_ = false;
        bitField0_ = (bitField0_ & ~0x00000200);
        rank_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        model_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        nationality_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        avaters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
        signature_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        constellation_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00010000);
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00020000);
        city_ = "";
        bitField0_ = (bitField0_ & ~0x00040000);
        genLon_ = 0F;
        bitField0_ = (bitField0_ & ~0x00080000);
        genLat_ = 0F;
        bitField0_ = (bitField0_ & ~0x00100000);
        ladderAddStarScore_ = 0;
        bitField0_ = (bitField0_ & ~0x00200000);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xmbl.ops.proto.PbPlayerEntity.internal_static_PbPlayer_descriptor;
      }

      @java.lang.Override
      public com.xmbl.ops.proto.PbPlayerEntity.PbPlayer getDefaultInstanceForType() {
        return com.xmbl.ops.proto.PbPlayerEntity.PbPlayer.getDefaultInstance();
      }

      @java.lang.Override
      public com.xmbl.ops.proto.PbPlayerEntity.PbPlayer build() {
        com.xmbl.ops.proto.PbPlayerEntity.PbPlayer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xmbl.ops.proto.PbPlayerEntity.PbPlayer buildPartial() {
        com.xmbl.ops.proto.PbPlayerEntity.PbPlayer result = new com.xmbl.ops.proto.PbPlayerEntity.PbPlayer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.curServerId_ = curServerId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ladderLv_ = ladderLv_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.ladderStar_ = ladderStar_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.avatar_ = avatar_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.needGuild_ = needGuild_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.rank_ = rank_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.model_ = model_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.nationality_ = nationality_;
        if (((bitField0_ & 0x00002000) == 0x00002000)) {
          avaters_ = java.util.Collections.unmodifiableList(avaters_);
          bitField0_ = (bitField0_ & ~0x00002000);
        }
        result.avaters_ = avaters_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.signature_ = signature_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.constellation_ = constellation_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.age_ = age_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.city_ = city_;
        if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.genLon_ = genLon_;
        if (((from_bitField0_ & 0x00100000) == 0x00100000)) {
          to_bitField0_ |= 0x00080000;
        }
        result.genLat_ = genLat_;
        if (((from_bitField0_ & 0x00200000) == 0x00200000)) {
          to_bitField0_ |= 0x00100000;
        }
        result.ladderAddStarScore_ = ladderAddStarScore_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xmbl.ops.proto.PbPlayerEntity.PbPlayer) {
          return mergeFrom((com.xmbl.ops.proto.PbPlayerEntity.PbPlayer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xmbl.ops.proto.PbPlayerEntity.PbPlayer other) {
        if (other == com.xmbl.ops.proto.PbPlayerEntity.PbPlayer.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasCurServerId()) {
          setCurServerId(other.getCurServerId());
        }
        if (other.hasLadderLv()) {
          setLadderLv(other.getLadderLv());
        }
        if (other.hasLadderStar()) {
          setLadderStar(other.getLadderStar());
        }
        if (other.hasAvatar()) {
          bitField0_ |= 0x00000080;
          avatar_ = other.avatar_;
          onChanged();
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasNeedGuild()) {
          setNeedGuild(other.getNeedGuild());
        }
        if (other.hasRank()) {
          setRank(other.getRank());
        }
        if (other.hasModel()) {
          setModel(other.getModel());
        }
        if (other.hasNationality()) {
          setNationality(other.getNationality());
        }
        if (!other.avaters_.isEmpty()) {
          if (avaters_.isEmpty()) {
            avaters_ = other.avaters_;
            bitField0_ = (bitField0_ & ~0x00002000);
          } else {
            ensureAvatersIsMutable();
            avaters_.addAll(other.avaters_);
          }
          onChanged();
        }
        if (other.hasSignature()) {
          bitField0_ |= 0x00004000;
          signature_ = other.signature_;
          onChanged();
        }
        if (other.hasConstellation()) {
          setConstellation(other.getConstellation());
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasCity()) {
          bitField0_ |= 0x00040000;
          city_ = other.city_;
          onChanged();
        }
        if (other.hasGenLon()) {
          setGenLon(other.getGenLon());
        }
        if (other.hasGenLat()) {
          setGenLat(other.getGenLat());
        }
        if (other.hasLadderAddStarScore()) {
          setLadderAddStarScore(other.getLadderAddStarScore());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xmbl.ops.proto.PbPlayerEntity.PbPlayer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xmbl.ops.proto.PbPlayerEntity.PbPlayer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <pre>
       *角色唯一id
       * </pre>
       *
       * <code>required int64 Id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *角色唯一id
       * </pre>
       *
       * <code>required int64 Id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *角色唯一id
       * </pre>
       *
       * <code>required int64 Id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *角色唯一id
       * </pre>
       *
       * <code>required int64 Id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *角色名称
       * </pre>
       *
       * <code>optional string Name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *角色名称
       * </pre>
       *
       * <code>optional string Name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *角色名称
       * </pre>
       *
       * <code>optional string Name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *角色名称
       * </pre>
       *
       * <code>optional string Name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *角色名称
       * </pre>
       *
       * <code>optional string Name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *角色名称
       * </pre>
       *
       * <code>optional string Name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <pre>
       *角色等级
       * </pre>
       *
       * <code>optional int32 Level = 3;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *角色等级
       * </pre>
       *
       * <code>optional int32 Level = 3;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <pre>
       *角色等级
       * </pre>
       *
       * <code>optional int32 Level = 3;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000004;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *角色等级
       * </pre>
       *
       * <code>optional int32 Level = 3;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        onChanged();
        return this;
      }

      private int serverId_ ;
      /**
       * <pre>
       *服务器ID
       * </pre>
       *
       * <code>optional int32 ServerId = 4;</code>
       */
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *服务器ID
       * </pre>
       *
       * <code>optional int32 ServerId = 4;</code>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <pre>
       *服务器ID
       * </pre>
       *
       * <code>optional int32 ServerId = 4;</code>
       */
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000008;
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器ID
       * </pre>
       *
       * <code>optional int32 ServerId = 4;</code>
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        serverId_ = 0;
        onChanged();
        return this;
      }

      private int curServerId_ ;
      /**
       * <pre>
       *当前所在服ID   有可能处于战斗服
       * </pre>
       *
       * <code>optional int32 CurServerId = 5;</code>
       */
      public boolean hasCurServerId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *当前所在服ID   有可能处于战斗服
       * </pre>
       *
       * <code>optional int32 CurServerId = 5;</code>
       */
      public int getCurServerId() {
        return curServerId_;
      }
      /**
       * <pre>
       *当前所在服ID   有可能处于战斗服
       * </pre>
       *
       * <code>optional int32 CurServerId = 5;</code>
       */
      public Builder setCurServerId(int value) {
        bitField0_ |= 0x00000010;
        curServerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前所在服ID   有可能处于战斗服
       * </pre>
       *
       * <code>optional int32 CurServerId = 5;</code>
       */
      public Builder clearCurServerId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        curServerId_ = 0;
        onChanged();
        return this;
      }

      private int ladderLv_ ;
      /**
       * <pre>
       *天梯等级
       * </pre>
       *
       * <code>optional int32 LadderLv = 6;</code>
       */
      public boolean hasLadderLv() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       *天梯等级
       * </pre>
       *
       * <code>optional int32 LadderLv = 6;</code>
       */
      public int getLadderLv() {
        return ladderLv_;
      }
      /**
       * <pre>
       *天梯等级
       * </pre>
       *
       * <code>optional int32 LadderLv = 6;</code>
       */
      public Builder setLadderLv(int value) {
        bitField0_ |= 0x00000020;
        ladderLv_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *天梯等级
       * </pre>
       *
       * <code>optional int32 LadderLv = 6;</code>
       */
      public Builder clearLadderLv() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ladderLv_ = 0;
        onChanged();
        return this;
      }

      private int ladderStar_ ;
      /**
       * <pre>
       *天梯星数
       * </pre>
       *
       * <code>optional int32 LadderStar = 7;</code>
       */
      public boolean hasLadderStar() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       *天梯星数
       * </pre>
       *
       * <code>optional int32 LadderStar = 7;</code>
       */
      public int getLadderStar() {
        return ladderStar_;
      }
      /**
       * <pre>
       *天梯星数
       * </pre>
       *
       * <code>optional int32 LadderStar = 7;</code>
       */
      public Builder setLadderStar(int value) {
        bitField0_ |= 0x00000040;
        ladderStar_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *天梯星数
       * </pre>
       *
       * <code>optional int32 LadderStar = 7;</code>
       */
      public Builder clearLadderStar() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ladderStar_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object avatar_ = "";
      /**
       * <pre>
       *头像图片
       * </pre>
       *
       * <code>optional string Avatar = 8;</code>
       */
      public boolean hasAvatar() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       *头像图片
       * </pre>
       *
       * <code>optional string Avatar = 8;</code>
       */
      public java.lang.String getAvatar() {
        java.lang.Object ref = avatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            avatar_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *头像图片
       * </pre>
       *
       * <code>optional string Avatar = 8;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarBytes() {
        java.lang.Object ref = avatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *头像图片
       * </pre>
       *
       * <code>optional string Avatar = 8;</code>
       */
      public Builder setAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像图片
       * </pre>
       *
       * <code>optional string Avatar = 8;</code>
       */
      public Builder clearAvatar() {
        bitField0_ = (bitField0_ & ~0x00000080);
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像图片
       * </pre>
       *
       * <code>optional string Avatar = 8;</code>
       */
      public Builder setAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        avatar_ = value;
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <pre>
       *状态
       * </pre>
       *
       * <code>optional int32 State = 9;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <pre>
       *状态
       * </pre>
       *
       * <code>optional int32 State = 9;</code>
       */
      public int getState() {
        return state_;
      }
      /**
       * <pre>
       *状态
       * </pre>
       *
       * <code>optional int32 State = 9;</code>
       */
      public Builder setState(int value) {
        bitField0_ |= 0x00000100;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *状态
       * </pre>
       *
       * <code>optional int32 State = 9;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000100);
        state_ = 0;
        onChanged();
        return this;
      }

      private boolean needGuild_ ;
      /**
       * <pre>
       *是否需要新手引导
       * </pre>
       *
       * <code>optional bool NeedGuild = 10;</code>
       */
      public boolean hasNeedGuild() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <pre>
       *是否需要新手引导
       * </pre>
       *
       * <code>optional bool NeedGuild = 10;</code>
       */
      public boolean getNeedGuild() {
        return needGuild_;
      }
      /**
       * <pre>
       *是否需要新手引导
       * </pre>
       *
       * <code>optional bool NeedGuild = 10;</code>
       */
      public Builder setNeedGuild(boolean value) {
        bitField0_ |= 0x00000200;
        needGuild_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否需要新手引导
       * </pre>
       *
       * <code>optional bool NeedGuild = 10;</code>
       */
      public Builder clearNeedGuild() {
        bitField0_ = (bitField0_ & ~0x00000200);
        needGuild_ = false;
        onChanged();
        return this;
      }

      private int rank_ ;
      /**
       * <pre>
       *排行信息
       * </pre>
       *
       * <code>optional int32 Rank = 11;</code>
       */
      public boolean hasRank() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <pre>
       *排行信息
       * </pre>
       *
       * <code>optional int32 Rank = 11;</code>
       */
      public int getRank() {
        return rank_;
      }
      /**
       * <pre>
       *排行信息
       * </pre>
       *
       * <code>optional int32 Rank = 11;</code>
       */
      public Builder setRank(int value) {
        bitField0_ |= 0x00000400;
        rank_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *排行信息
       * </pre>
       *
       * <code>optional int32 Rank = 11;</code>
       */
      public Builder clearRank() {
        bitField0_ = (bitField0_ & ~0x00000400);
        rank_ = 0;
        onChanged();
        return this;
      }

      private int model_ ;
      /**
       * <pre>
       *角色人物模型
       * </pre>
       *
       * <code>optional int32 Model = 12;</code>
       */
      public boolean hasModel() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <pre>
       *角色人物模型
       * </pre>
       *
       * <code>optional int32 Model = 12;</code>
       */
      public int getModel() {
        return model_;
      }
      /**
       * <pre>
       *角色人物模型
       * </pre>
       *
       * <code>optional int32 Model = 12;</code>
       */
      public Builder setModel(int value) {
        bitField0_ |= 0x00000800;
        model_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *角色人物模型
       * </pre>
       *
       * <code>optional int32 Model = 12;</code>
       */
      public Builder clearModel() {
        bitField0_ = (bitField0_ & ~0x00000800);
        model_ = 0;
        onChanged();
        return this;
      }

      private int nationality_ ;
      /**
       * <pre>
       *星座
       * </pre>
       *
       * <code>optional int32 Nationality = 13;</code>
       */
      public boolean hasNationality() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <pre>
       *星座
       * </pre>
       *
       * <code>optional int32 Nationality = 13;</code>
       */
      public int getNationality() {
        return nationality_;
      }
      /**
       * <pre>
       *星座
       * </pre>
       *
       * <code>optional int32 Nationality = 13;</code>
       */
      public Builder setNationality(int value) {
        bitField0_ |= 0x00001000;
        nationality_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *星座
       * </pre>
       *
       * <code>optional int32 Nationality = 13;</code>
       */
      public Builder clearNationality() {
        bitField0_ = (bitField0_ & ~0x00001000);
        nationality_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> avaters_ = java.util.Collections.emptyList();
      private void ensureAvatersIsMutable() {
        if (!((bitField0_ & 0x00002000) == 0x00002000)) {
          avaters_ = new java.util.ArrayList<java.lang.Integer>(avaters_);
          bitField0_ |= 0x00002000;
         }
      }
      /**
       * <pre>
       *装扮
       * </pre>
       *
       * <code>repeated int32 Avaters = 14;</code>
       */
      public java.util.List<java.lang.Integer>
          getAvatersList() {
        return java.util.Collections.unmodifiableList(avaters_);
      }
      /**
       * <pre>
       *装扮
       * </pre>
       *
       * <code>repeated int32 Avaters = 14;</code>
       */
      public int getAvatersCount() {
        return avaters_.size();
      }
      /**
       * <pre>
       *装扮
       * </pre>
       *
       * <code>repeated int32 Avaters = 14;</code>
       */
      public int getAvaters(int index) {
        return avaters_.get(index);
      }
      /**
       * <pre>
       *装扮
       * </pre>
       *
       * <code>repeated int32 Avaters = 14;</code>
       */
      public Builder setAvaters(
          int index, int value) {
        ensureAvatersIsMutable();
        avaters_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *装扮
       * </pre>
       *
       * <code>repeated int32 Avaters = 14;</code>
       */
      public Builder addAvaters(int value) {
        ensureAvatersIsMutable();
        avaters_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *装扮
       * </pre>
       *
       * <code>repeated int32 Avaters = 14;</code>
       */
      public Builder addAllAvaters(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureAvatersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, avaters_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *装扮
       * </pre>
       *
       * <code>repeated int32 Avaters = 14;</code>
       */
      public Builder clearAvaters() {
        avaters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
        onChanged();
        return this;
      }

      private java.lang.Object signature_ = "";
      /**
       * <pre>
       *签名
       * </pre>
       *
       * <code>optional string Signature = 15;</code>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <pre>
       *签名
       * </pre>
       *
       * <code>optional string Signature = 15;</code>
       */
      public java.lang.String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            signature_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *签名
       * </pre>
       *
       * <code>optional string Signature = 15;</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        java.lang.Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *签名
       * </pre>
       *
       * <code>optional string Signature = 15;</code>
       */
      public Builder setSignature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *签名
       * </pre>
       *
       * <code>optional string Signature = 15;</code>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00004000);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *签名
       * </pre>
       *
       * <code>optional string Signature = 15;</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        signature_ = value;
        onChanged();
        return this;
      }

      private int constellation_ ;
      /**
       * <pre>
       *国家
       * </pre>
       *
       * <code>optional int32 Constellation = 16;</code>
       */
      public boolean hasConstellation() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <pre>
       *国家
       * </pre>
       *
       * <code>optional int32 Constellation = 16;</code>
       */
      public int getConstellation() {
        return constellation_;
      }
      /**
       * <pre>
       *国家
       * </pre>
       *
       * <code>optional int32 Constellation = 16;</code>
       */
      public Builder setConstellation(int value) {
        bitField0_ |= 0x00008000;
        constellation_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *国家
       * </pre>
       *
       * <code>optional int32 Constellation = 16;</code>
       */
      public Builder clearConstellation() {
        bitField0_ = (bitField0_ & ~0x00008000);
        constellation_ = 0;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <pre>
       *年龄
       * </pre>
       *
       * <code>optional int32 Age = 17;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <pre>
       *年龄
       * </pre>
       *
       * <code>optional int32 Age = 17;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       *年龄
       * </pre>
       *
       * <code>optional int32 Age = 17;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00010000;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *年龄
       * </pre>
       *
       * <code>optional int32 Age = 17;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00010000);
        age_ = 0;
        onChanged();
        return this;
      }

      private int sex_ ;
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>optional int32 Sex = 18;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>optional int32 Sex = 18;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>optional int32 Sex = 18;</code>
       */
      public Builder setSex(int value) {
        bitField0_ |= 0x00020000;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>optional int32 Sex = 18;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00020000);
        sex_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <pre>
       *城市
       * </pre>
       *
       * <code>optional string City = 19;</code>
       */
      public boolean hasCity() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      /**
       * <pre>
       *城市
       * </pre>
       *
       * <code>optional string City = 19;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            city_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *城市
       * </pre>
       *
       * <code>optional string City = 19;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *城市
       * </pre>
       *
       * <code>optional string City = 19;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00040000;
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *城市
       * </pre>
       *
       * <code>optional string City = 19;</code>
       */
      public Builder clearCity() {
        bitField0_ = (bitField0_ & ~0x00040000);
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *城市
       * </pre>
       *
       * <code>optional string City = 19;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00040000;
        city_ = value;
        onChanged();
        return this;
      }

      private float genLon_ ;
      /**
       * <pre>
       *坐标经度
       * </pre>
       *
       * <code>optional float GenLon = 20;</code>
       */
      public boolean hasGenLon() {
        return ((bitField0_ & 0x00080000) == 0x00080000);
      }
      /**
       * <pre>
       *坐标经度
       * </pre>
       *
       * <code>optional float GenLon = 20;</code>
       */
      public float getGenLon() {
        return genLon_;
      }
      /**
       * <pre>
       *坐标经度
       * </pre>
       *
       * <code>optional float GenLon = 20;</code>
       */
      public Builder setGenLon(float value) {
        bitField0_ |= 0x00080000;
        genLon_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *坐标经度
       * </pre>
       *
       * <code>optional float GenLon = 20;</code>
       */
      public Builder clearGenLon() {
        bitField0_ = (bitField0_ & ~0x00080000);
        genLon_ = 0F;
        onChanged();
        return this;
      }

      private float genLat_ ;
      /**
       * <pre>
       *坐标纬度
       * </pre>
       *
       * <code>optional float GenLat = 21;</code>
       */
      public boolean hasGenLat() {
        return ((bitField0_ & 0x00100000) == 0x00100000);
      }
      /**
       * <pre>
       *坐标纬度
       * </pre>
       *
       * <code>optional float GenLat = 21;</code>
       */
      public float getGenLat() {
        return genLat_;
      }
      /**
       * <pre>
       *坐标纬度
       * </pre>
       *
       * <code>optional float GenLat = 21;</code>
       */
      public Builder setGenLat(float value) {
        bitField0_ |= 0x00100000;
        genLat_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *坐标纬度
       * </pre>
       *
       * <code>optional float GenLat = 21;</code>
       */
      public Builder clearGenLat() {
        bitField0_ = (bitField0_ & ~0x00100000);
        genLat_ = 0F;
        onChanged();
        return this;
      }

      private int ladderAddStarScore_ ;
      /**
       * <pre>
       *天梯分数
       * </pre>
       *
       * <code>optional int32 LadderAddStarScore = 22;</code>
       */
      public boolean hasLadderAddStarScore() {
        return ((bitField0_ & 0x00200000) == 0x00200000);
      }
      /**
       * <pre>
       *天梯分数
       * </pre>
       *
       * <code>optional int32 LadderAddStarScore = 22;</code>
       */
      public int getLadderAddStarScore() {
        return ladderAddStarScore_;
      }
      /**
       * <pre>
       *天梯分数
       * </pre>
       *
       * <code>optional int32 LadderAddStarScore = 22;</code>
       */
      public Builder setLadderAddStarScore(int value) {
        bitField0_ |= 0x00200000;
        ladderAddStarScore_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *天梯分数
       * </pre>
       *
       * <code>optional int32 LadderAddStarScore = 22;</code>
       */
      public Builder clearLadderAddStarScore() {
        bitField0_ = (bitField0_ & ~0x00200000);
        ladderAddStarScore_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PbPlayer)
    }

    // @@protoc_insertion_point(class_scope:PbPlayer)
    private static final com.xmbl.ops.proto.PbPlayerEntity.PbPlayer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xmbl.ops.proto.PbPlayerEntity.PbPlayer();
    }

    public static com.xmbl.ops.proto.PbPlayerEntity.PbPlayer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PbPlayer>
        PARSER = new com.google.protobuf.AbstractParser<PbPlayer>() {
      @java.lang.Override
      public PbPlayer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PbPlayer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PbPlayer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PbPlayer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xmbl.ops.proto.PbPlayerEntity.PbPlayer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PbPlayer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PbPlayer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024PbPlayerEntity.proto\"\203\003\n\010PbPlayer\022\n\n\002I" +
      "d\030\001 \002(\003\022\014\n\004Name\030\002 \001(\t\022\r\n\005Level\030\003 \001(\005\022\020\n\010" +
      "ServerId\030\004 \001(\005\022\023\n\013CurServerId\030\005 \001(\005\022\020\n\010L" +
      "adderLv\030\006 \001(\005\022\022\n\nLadderStar\030\007 \001(\005\022\016\n\006Ava" +
      "tar\030\010 \001(\t\022\r\n\005State\030\t \001(\005\022\021\n\tNeedGuild\030\n " +
      "\001(\010\022\014\n\004Rank\030\013 \001(\005\022\r\n\005Model\030\014 \001(\005\022\023\n\013Nati" +
      "onality\030\r \001(\005\022\017\n\007Avaters\030\016 \003(\005\022\021\n\tSignat" +
      "ure\030\017 \001(\t\022\025\n\rConstellation\030\020 \001(\005\022\013\n\003Age\030" +
      "\021 \001(\005\022\013\n\003Sex\030\022 \001(\005\022\014\n\004City\030\023 \001(\t\022\016\n\006GenL" +
      "on\030\024 \001(\002\022\016\n\006GenLat\030\025 \001(\002\022\032\n\022LadderAddSta" +
      "rScore\030\026 \001(\005B$\n\022com.xmbl.ops.protoB\016PbPl" +
      "ayerEntity"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PbPlayer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PbPlayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PbPlayer_descriptor,
        new java.lang.String[] { "Id", "Name", "Level", "ServerId", "CurServerId", "LadderLv", "LadderStar", "Avatar", "State", "NeedGuild", "Rank", "Model", "Nationality", "Avaters", "Signature", "Constellation", "Age", "Sex", "City", "GenLon", "GenLat", "LadderAddStarScore", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
